[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@solady/contracts/=lib/solady/src/',
]

[rpc_endpoints]
optimism = "${OPTIMISM_RPC}"
optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC}" 

[etherscan]
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", chain = 10 }
optimism-sepolia = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", chain = 11155420 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
